language: ruby
rvm:
  - 1.8.7
  - 2.1.0
before_install:
  - gem update --system 2.1.11
  - gem --version
  - gem install bundler
before_script:
  - cp spec/config/gitcycle.example.yml spec/config/gitcycle.yml